### ISSUE TITLE
Add Package Script for running Client and Concurrently

### ISSUE THREAD

**Issue by Anushika09** [Anushika09/Leave-Tracker#7]

**Comment by iyosayi** [comment]
Can this be assigned to me?

**Comment by UnbiasedEagle** [comment]
Hey is client a react app?

**Comment by Anushika09** [comment]
> Hey is client a react app?

You are needed to make a client folder now and assemble current app

**Comment by UnbiasedEagle** [comment]
current app is react app right ?

**Comment by Anushika09** [comment]
> current app is react app right ?

Yes @UnbiasedEagle

**Comment by UnbiasedEagle** [comment]
k I will be very happy to help you in this issue.

**Comment by UnbiasedEagle** [comment]
Hey somebody has already done it and you have also merged it

**Comment by Anushika09** [comment]
> Hey somebody has already done it and you have also merged it

Due to Improper Folder Structure Package.json file have been removed @UnbiasedEagle
